import React from 'react';
import { PrimeReactProvider } from 'primereact/api';
import type { Metadata } from 'next';
import { Inter } from "next/font/google";
import './globals.css';
import "primereact/resources/themes/lara-light-indigo/theme.css";
import 'primeicons/primeicons.css';
import AppTopbar from '@/layout/AppTopbar';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>): React.ReactNode {
  return (
    <html lang="en">
      <PrimeReactProvider >     
        <AppTopbar/>    
        <body className={inter.className}>{children}</body>
      </PrimeReactProvider>
    </html>
  )
}
